name: Tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Tests:
    runs-on: macos-26-xlarge
    steps:
    - name: Cancel previous jobs
      uses: styfle/cancel-workflow-action@0.12.1

    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Load Latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build project
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -destination 'name=iPhone 17 Pro,OS=26.0' -scheme 'PovioKit-Package' | xcpretty

    - name: Run tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -destination 'name=iPhone 17 Pro,OS=26.0' -scheme 'PovioKit-Package' | xcpretty      
